version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: tourmate-db
    restart: always
    environment:
      POSTGRES_USER: tourmate_user
      POSTGRES_PASSWORD: tourmate_pass
      POSTGRES_DB: tourmate
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: tourmate-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tourmate.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"

volumes:
  pg_data: